project:
  type: website
  output-dir: docs

website:
  title: "BayesCoverage"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: bayescoverage.qmd
        text: Coverage modeling 
      - href: software.qmd
        text: Software
      - href: fpet.qmd
        text: FPET
      - href: modules.qmd
        text: Training - let’s go Bayesian

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true


editor: visual

