---
title: "Family Planning Estimation Tool (FPET)"
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
---

# Summary

The Family Planning Estimation Tool (FPET) was designed to produce annual estimates and forecasts of family planning indicators such as modern contraceptive use (mCPR), unmet need, and demand satisfied by modern methods. FPET considers survey data, service statistics (where determined to be of adequate quality), and regional and global historical patterns of change to produce annual estimates beyond the last survey and into the future.

The current modeling approach is described in Alkema et al. (2024). This approach builds off collaborative research with the United Nations Population Division (UNPD). References to earlier and related work are included below.

This work was supported, in whole or in part, by the Gates Foundation (INV-00844).

## References:

- FPET overview: L. Alkema, H. Susmann, E. Ray, S. Mooney, N. Cahill, K. Bietsch, A. Jayachandran, et al. (2024). Bayesian Statistical Modeling in Action for Estimation and Forecasting in Low- and Middle-income Countries: The Case of the Family Planning Estimation Tool. See <https://doi.org/10.48550/arXiv.2501.00007>.

- Use of service statistics data (Estimated modern use): S. Mooney, L. Alkema, E. Sonneveldt, K. Bietsch, J. Williamson, N. Cahill (2024). Enhancing the Use of Family Planning Service Statistics Using a Bayesian Modelling Approach to Inform Estimates of Modern Contraceptive Use in Low- and Middle-Income Countries. See <https://doi.org/10.48550/arXiv.2412.08606>.

References that describe earlier approaches:

- Alkema, L. et al. (2013). National, regional and global rates and trends in contraceptive prevalence and unmet need for family planning between 1990 and 2015: a systematic and comprehensive analysis. The Lancet. Available at <http://www.thelancet.com/journals/lancet/article/PIIS0140-6736(12)62204-1/abstract>.

- Cahill et al., (2017). Modern contraceptive use, unmet need, and demand satisfied among women of reproductive age who are married or in a union in the focus countries of the Family Planning 2020 initiative: a systematic analysis using the Family Planning Estimation Tool. The Lancet. Available at <http://www.thelancet.com/journals/lancet/article/PIIS0140-6736(17)33104-5/fulltext>.

- Kantorova et al. (2020). Estimating progress towardsmeeting women’s contraceptive needs in 185 countries: A Bayesian hierarchical modellingstudy. PLOS Medicine, 17(2):e1003026. Available at <https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1003026>.

- Wheldon et al. (2018). Methods for estimating and projecting key family planning indicators among all women of reproductive age. United Nations, Department of Economic and Social Affairs, Population Division, Technical Paper No. 2. New York: United Nations. Available at <https://www.un.org/en/development/desa/population/publications/pdf/technical/TP2018-2.pdf>.

# Software

The model is written in R and Stan. The R package is available at <https://github.com/AlkemaLab/fpet2> and described at <https://alkemalab.github.io/fpet2/>. For any questions, feedback or suggestions, please contact Leontine at lalkema(at)umass.edu.

An online app by the Track20 project is available at <https://fpet.track20.org/>.
